---
- name: Destroy servers.
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  vars: 
    hcloud_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"

  vars_files:
  - config.yml

  tasks:
  - name: Destroy servers.
    hcloud_server:
      api_token: "{{ hcloud_token }}"
      name: "{{ server_name }}"
      state: absent
    register: server
